# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_user_real_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=20, unique=True, verbose_name='银行卡号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User', verbose_name='关联用户')),
            ],
        ),
    ]
