# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='owner',
        ),
    ]
