# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_user_real_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, unique=True, verbose_name='商品类别')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('price', models.FloatField(default=0, verbose_name='商品单价')),
                ('store', models.IntegerField(default=0, verbose_name='库存')),
                ('pic', models.CharField(max_length=128, verbose_name='商品图片')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Good.Category', verbose_name='所属商品类别')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User', verbose_name='所属卖家')),
            ],
        ),
    ]
