# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_default_card'),
        ('Good', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_num', models.IntegerField(verbose_name='默认购买数量')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Good.Category', verbose_name='关联商品类别')),
                ('default_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Good.Good', verbose_name='默认购买商品')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User', verbose_name='关联用户')),
            ],
        ),
    ]
