# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Good', '0002_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.CharField(default=None, max_length=512, verbose_name='商品介绍'),
        ),
    ]
