# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_type', models.IntegerField(choices=[(0, '买家'), (1, '卖家')], help_text='买家和卖家', verbose_name='用户类型')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='MD5密码')),
                ('address', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='住址或仓库地址')),
                ('brand', models.CharField(max_length=32, verbose_name='卖家商家品牌')),
            ],
        ),
    ]
