# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='真实姓名'),
        ),
    ]
