# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Card', '0002_auto_20170705_1131'),
        ('User', '0002_user_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Card.Card', verbose_name='默认银行卡'),
        ),
    ]
