# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_default_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.IntegerField(default=0, verbose_name='头像编号'),
        ),
    ]
