# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0003_user_default_card'),
        ('Good', '0003_good_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('real_name', models.CharField(max_length=64, verbose_name='买家姓名')),
                ('address', models.CharField(max_length=512, verbose_name='买家地址')),
                ('good_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('buy_num', models.IntegerField(default=0, verbose_name='购买数量')),
                ('price', models.FloatField(default=0, verbose_name='购买时单价')),
                ('deliver_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='发货时间')),
                ('status', models.IntegerField(choices=[(5, '确认接单'), (6, '确认发货'), (7, '确认收货')], default=5, verbose_name='订单状态')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User', verbose_name='买家')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Good.Good', verbose_name='商品')),
            ],
        ),
    ]
